export const AnahtarType = [
  { value: 'KONUT', label: 'KONUT' },
  { value: 'DAİRE', label: 'DAİRE' },
  { value: 'VİLLA', label: 'VİLLA' },
  { value: 'OTEL', label: 'OTEL' },
  { value: 'RESTORAN', label: 'RESTORAN' },
  { value: 'CAFE', label: 'CAFE' },
  { value: 'BAR', label: 'BAR' },
  { value: 'SOSYAL TESİS', label: 'SOSYAL TESİS' },
  { value: 'OFİS', label: 'OFİS' },
  { value: 'OTOPARK', label: 'OTOPARK' },
  { value: 'PARK', label: 'PARK' },
  { value: 'MOTEL', label: 'MOTEL' },
  { value: 'SERGİ ALANI', label: 'SERGİ ALANI' },
  { value: 'GALERİ', label: 'GALERİ' },
  { value: 'ALIŞVERİŞ MERKEZİ', label: 'ALIŞVERİŞ MERKEZİ' },
  { value: 'MAĞAZA', label: 'MAĞAZA' },
  { value: 'SHOWRROM', label: 'SHOWRROM' },
  { value: 'SPOR MERKEZİ', label: 'SPOR MERKEZİ' },
  { value: 'HASTANE', label: 'HASTANE' },
  { value: 'KONSER SALONU', label: 'KONSER SALONU' },
  { value: 'KUYUMCU', label: 'KUYUMCU' },
  { value: 'GELİNLİKÇİ', label: 'GELİNLİKÇİ' },
  { value: 'MÜZE', label: 'MÜZE' },
  { value: 'KÜTÜPHANE', label: 'KÜTÜPHANE' },
  { value: 'KAPALI YÜZME HAVUZU', label: 'KAPALI YÜZME HAVUZU' },
  { value: 'BİNA', label: 'BİNA' },
  { value: 'SALON', label: 'SALON' },
  { value: 'BANYO-WC', label: 'BANYO-WC' },
  { value: 'YEMEK ODASI', label: 'YEMEK ODASI' },
  { value: 'YATAK ODASI', label: 'YATAK ODASI' },
  { value: 'ÇOCUK ODASI', label: 'ÇOCUK ODASI' },
  { value: 'GİYİNME ODASI', label: 'GİYİNME ODASI' },
  { value: 'MİSAFİR ODASI', label: 'MİSAFİR ODASI' },
  { value: 'OTURMA ODASI', label: 'OTURMA ODASI' },
  { value: 'ÇALIŞMA ODASI', label: 'ÇALIŞMA ODASI' },
  { value: 'MUTFAK ODASI', label: 'MUTFAK ODASI' },
  { value: 'GENÇ ODASI', label: 'GENÇ ODASI' },
  { value: 'GÜZELLİK MERKEZİ', label: 'GÜZELLİK MERKEZİ' },
  { value: 'BERBER-KUAFÖR', label: 'BERBER-KUAFÖR' },
  { value: 'BANKA', label: 'BANKA' },
  { value: 'EMLAK', label: 'EMLAK' },
  { value: 'BAHÇE', label: 'BAHÇE' },
  { value: 'PARK', label: 'PARK' },
  { value: 'DIŞ CEPHE', label: 'DIŞ CEPHE' },
]
