export const AnahtarSub = [
    { value: "ANAHTAR TESLİM TADİLAT" , label: "ANAHTAR TESLİM TADİLAT"},
    { value: "ANAHTAR TESLİM KIR EVI" , label: "ANAHTAR TESLİM KIR EVİ"},
    { value: "KISMI TADİLAT" , label: "KISMI TADİLAT"},
    { value: "ANAHTAR TESLİM İNŞAAT" , label: "ANAHTAR TESLİM İNŞAAT"},
    { value: " ANAHTAR TESLİM İŞÇİLİK" , label: " ANAHTAR TESLİM İŞÇİLİK"},
    { value: "ANAHTAR TESLİM ÇİFTLİK EVİ" , label: "ANAHTAR TESLİM ÇİFTLİK EVİ"},
    { value: "ANAHTART TESLİM KÖY EVİ" , label: "ANAHTART TESLİM KÖY EVİ"},
    { value: "ANAHTAR TESLİM PREFABRİK YAPI" , label: "ANAHTAR TESLİM PREFABRİK YAPI"},
    { value: "ANAHTAR TESLİM KONTEYNER" , label: "ANAHTAR TESLİM KONTEYNER"},
    { value: "ANAHTAR TESLİM TAŞ YAPI" , label: "ANAHTAR TESLİM TAŞ YAPI"},
    { value: "ANAHTAR TESLİM BUNGALOV" , label: "ANAHTAR TESLİM BUNGALOV"},
    { value: "ANAHTAR TESLİM TAŞINABİLİR EV" , label: "ANAHTAR TESLİM TAŞINABİLİR EV"},
    { value: "ANAHTAR TESLİM MÜSTKİL EV" , label: "ANAHTAR TESLİM MÜSTKİL EV"},
    { value: "ANAHTAR TESLİM TİNY HOUSE" , label: "ANAHTAR TESLİM TİNY HOUSE"},
    { value: "ANAHTAR TESLİM ÇELİK KARKAS YAPI" , label: "ANAHTAR TESLİM ÇELİK KARKAS YAPI"},
    { value: "ANAHTAR TESLİM YIĞMA KAGİR BİNA" , label: "ANAHTAR TESLİM YIĞMA KAGİR BİNA"},
    { value: "ANAHTAR TESLİM AHŞAP BİNA" , label: "ANAHTAR TESLİM AHŞAP BİNA"},
    { value: "ANAHTAR TESLİM KABA İNŞAAT" , label: "ANAHTAR TESLİM KABA İNŞAAT"},
    { value: "ANAHTAR TESLİM RESTORASYON" , label: "ANAHTAR TESLİM RESTORASYON"},
]