export const DisSub = [
  {
    value: 'TOTEM',
    label: 'TOTEM',
  },
  { value: 'TABELA', label: 'TABELA' },
  { value: 'İÇ MEKAN REKLAM', label: 'İÇ MEKAN REKLAM' },
  { value: 'ARAÇ REKLAM', label: 'ARAÇ REKLAM' },
  { value: 'CEPHE REKLAM', label: 'CEPHE REKLAM' },
  { value: 'PİLON', label: 'PİLON' },
  { value: 'YÖNLENDİRME TABELALARI', label: 'YÖNLENDİRME TABELALARI' },
  { value: 'NEON TABELA', label: 'NEON TABELA' },
  { value: 'IŞIKLI KUTU HARF TABELA', label: 'IŞIKLI KUTU HARF TABELA' },
  { value: 'IŞIKSIZ KUTU HARF TABELA', label: 'IŞIKSIZ KUTU HARF TABELA' },
  { value: 'ÇATI TABELALARI', label: 'ÇATI TABELALARI' },
  { value: 'PASLANMAZ TABELA', label: 'PASLANMAZ TABELA' },
  { value: 'PLEKSİ TABELA', label: 'PLEKSİ TABELA' },
  { value: 'LİGHTBOX TABELA', label: 'LİGHTBOX TABELA' },
  {
    value: 'İÇ MEKAN YÖNLENDİRME TABELALARI',
    label: 'İÇ MEKAN YÖNLENDİRME TABELALARI',
  },
  { value: 'DİJİTAL BASKI', label: 'DİJİTAL BASKI' },
  { value: 'FUAR SİSTEMLERİ', label: 'FUAR SİSTEMLERİ' },
  { value: 'AÇIK HAVA REKLAMLARI', label: 'AÇIK HAVA REKLAMLARI' },
  { value: 'ÜRÜN STANDLARI', label: 'ÜRÜN STANDLARI' },
  { value: 'AFİŞ', label: 'AFİŞ' },
  { value: 'BROŞÜR', label: 'BROŞÜR' },
  { value: 'DERGİ', label: 'DERGİ' },
  { value: 'KARTON ÇANTA', label: 'KARTON ÇANTA' },
  { value: 'KATALOG', label: 'KATALOG' },
  { value: 'ANAHTARLIK', label: 'ANAHTARLIK' },
  { value: 'KURUMSAL KİMLİK', label: 'KURUMSAL KİMLİK' },
  { value: 'KİTAP', label: 'KİTAP' },
  { value: 'GRAFİK TASARIM', label: 'GRAFİK TASARIM' },
  { value: 'KARTVİSİT', label: 'KARTVİSİT' },
  { value: 'ÖZEL KUTU', label: 'ÖZEL KUTU' },
  { value: 'ÖZEL KLASÖR', label: 'ÖZEL KLASÖR' },
  { value: 'BAYRAKLI BASKI', label: 'BAYRAKLI BASKI' },
  { value: 'BRANDA', label: 'BRANDA' },
  {
    value: 'DİJİTAL BASKILI DUVAR KAĞIDI',
    label: 'DİJİTAL BASKILI DUVAR KAĞIDI',
  },
  { value: 'DEKOTA ÜRÜNLER', label: 'DEKOTA ÜRÜNLER' },
  { value: 'PLEKSİ ÜRÜNLER', label: 'PLEKSİ ÜRÜNLER' },
  { value: 'FOLYO ÜRÜNLER', label: 'FOLYO ÜRÜNLER' },
  { value: 'MESH BRANDA', label: 'MESH BRANDA' },
  { value: 'ONE WAY VİSİON', label: 'ONE WAY VİSİON' },
  { value: 'POSTER', label: 'POSTER' },
  { value: 'ZEMİN BASKI', label: 'ZEMİN BASKI' },
  { value: 'ALÜMİNYUM KUTU HARF', label: 'ALÜMİNYUM KUTU HARF' },
  { value: 'FENER TABELA', label: 'FENER TABELA' },
  { value: 'KOMPOZİT PLEXİ OYMA', label: 'KOMPOZİT PLEXİ OYMA' },
  { value: 'VİNİL GERME TABELA', label: 'VİNİL GERME TABELA' },
  { value: 'MAGNET', label: 'MAGNET' },
  { value: 'PROMOSYON TAKVİM', label: 'PROMOSYON TAKVİM' },
  { value: 'MAKBUZ', label: 'MAKBUZ' },
  { value: 'FATURA-İRSALİYE', label: 'FATURA-İRSALİYE' },
  { value: 'ANTETLİ ZARF', label: 'ANTETLİ ZARF' },
  { value: 'ANTETLİ KAĞIT', label: 'ANTETLİ KAĞIT' },
  { value: 'CEPLİ DOSYA', label: 'CEPLİ DOSYA' },
  { value: 'İNSERT', label: 'İNSERT' },
]
