export const MobilyaSub = [
  {
    value: 'MUTFAK DOLABI YAPIMI',
    label: 'MUTFAK DOLABI YAPIMI',
  },
  { value: 'BANYO DOLABI YAPIMI', label: 'BANYO DOLABI YAPIMI' },
  { value: 'DKONSOL', label: 'KONSOL' },
  { value: 'TV ÜNİTESİ', label: 'TV ÜNİTESİ' },
  { value: 'VESTİYER', label: 'VESTİYER' },
  { value: 'YATAK ODASI', label: 'YATAK ODASI' },
  { value: 'GİYİNME ODASI', label: 'GİYİNME ODASI' },
  { value: 'ÇALIŞMA MASASI', label: 'ÇALIŞMA MASASI' },
  { value: 'KİTAPLIK', label: 'KİTAPLIK' },
  { value: 'STAND', label: 'STAND' },
  { value: 'AYAKKABILIK', label: 'AYAKKABILIK' },
  { value: 'KİLER', label: 'KİLER' },
  { value: 'FUAR STANDLARI', label: 'FUAR STANDLARI' },
  { value: 'GARDIROP İMALATI', label: 'GARDIROP İMALATI' },
  { value: 'RAF STAND', label: 'RAF STAND' },
  { value: 'MASA', label: 'MASA' },
  { value: 'KOLTUK', label: 'KOLTUK' },
  { value: 'SANDALYE', label: 'SANDALYE' },
  { value: 'TOPLANTI MASASI', label: 'TOPLANTI MASASI' },
  { value: 'KAPI', label: 'KAPI' },
  { value: 'AYNA İMALATI', label: 'AYNA İMALATI' },
  { value: 'SEPERATÖR İMALATI', label: 'SEPERATÖR İMALATI' },
]
