export const OzelSub = [
  {
    value: '3D Studio Max',
    label: '3D Studio Max',
  },
  { value: 'AutoCAD', label: 'AutoCAD' },
  { value: 'TÜRKÇE', label: 'TÜRKÇE' },
  { value: 'İNGİLİZCE', label: 'İNGİLİZCE' },
  { value: 'ALMANCA', label: 'ALMANCA' },
  { value: 'FRANSIZCA', label: 'FRANSIZCA' },
  { value: 'SolidWorks', label: 'SolidWorks' },
  { value: 'CATIA', label: 'CATIA' },
  { value: 'Blender', label: 'Blender' },
  { value: 'Revit', label: 'Revit' },
  { value: 'SketchUp', label: 'SketchUp' },
  { value: 'KitchenDraw', label: 'KitchenDraw' },
  { value: 'Canva', label: 'Canva' },
  { value: 'GIMP', label: 'GIMP' },
  { value: 'Adobe Photoshop Express', label: 'Adobe Photoshop Express' },
  { value: 'Adobe Photoshop Light Room', label: 'Adobe Photoshop Light Room' },
  { value: 'Paint.NET', label: 'Paint.NET' },
  { value: 'Pixlr X', label: 'Pixlr X' },
  { value: 'Ashampoo Photo Optimizer', label: 'Ashampoo Photo Optimizer' },
  { value: 'Scribus ', label: 'Scribus ' },
  { value: 'Inkspace', label: 'Inkspace' },
  { value: 'Open Office Writer', label: 'Open Office Writer' },
  { value: 'MATEMATİK', label: 'MATEMATİK' },
  { value: 'FİZİK', label: 'FİZİK' },
  { value: 'FEN BİLGİSİ', label: 'FEN BİLGİSİ' },
  { value: 'İLKÖĞRETİM TAKVİYE', label: 'İLKÖĞRETİM TAKVİYE' },
  { value: 'PİYANO', label: 'PİYANO' },
  { value: 'GİTAR', label: 'GİTAR' },
  { value: 'COĞRAFYA', label: 'COĞRAFYA' },
  { value: 'KİMYA', label: 'KİMYA' },
  { value: 'BİYOLOJİ', label: 'BİYOLOJİ' },
  { value: 'TARİH', label: 'TARİH' },
  {
    value: 'DİN KÜLTÜRÜ VE AHLAK BİLGİSİ',
    label: 'DİN KÜLTÜRÜ VE AHLAK BİLGİSİ',
  },
  { value: 'TÜRK DİLİ VE EDEBİYATI', label: 'TÜRK DİLİ VE EDEBİYATI' },
  { value: 'VURMALI ÇALGILAR', label: 'VURMALI ÇALGILAR' },
  { value: 'NEFESLİ ÇALGILAR', label: 'NEFESLİ ÇALGILAR' },
  { value: 'TUŞLU ÇALGILAR', label: 'TUŞLU ÇALGILAR' },
  { value: 'TELLİ ÇALGILAR', label: 'TELLİ ÇALGILAR' },
  { value: 'YAYLI ÇALGILAR', label: 'YAYLI ÇALGILAR' },
  { value: 'ŞANTİYE İŞLERİ', label: 'ŞANTİYE İŞLERİ' },
  { value: 'MİMARLIK', label: 'MİMARLIK' },
  { value: 'TASARIM', label: 'TASARIM' },
]
