export const ProjeSub = [
  { value: 'MİMARİ PROJE', label: 'MİMARİ PROJE' },
  { value: '3D PROJE', label: '3D PROJE' },
  {
    value: 'STATİK-ELEKTİRİK-MEKANİK PAKET PROJE',
    label: 'STATİK-ELEKTİRİK-MEKANİK PAKET PROJE',
  },
  { value: 'DOĞALGAZ PROJESİ', label: 'DOĞALGAZ PROJESİ' },
  { value: 'ELEKTRİK PROJESİ', label: 'ELEKTRİK PROJESİ' },
  { value: 'STATİK PROJE', label: 'STATİK PROJE' },
  { value: 'MEKANİK PROJE', label: 'MEKANİK PROJE' },
  { value: 'TASARIM PROJELERİ', label: 'TASARIM PROJELERİ' },
  { value: 'MOBİLYA TASARIM PROJESİ', label: 'MOBİLYA TASARIM PROJESİ' },
  { value: 'MOBİLYA İMALAT PROJESİ', label: 'MOBİLYA İMALAT PROJESİ' },
  { value: 'YERLEŞİM PROJESİ', label: 'YERLEŞİM PROJESİ' },
  { value: 'METRAJ -KEŞİF PROJESİ', label: 'METRAJ -KEŞİF PROJESİ' },
  { value: 'MALİYET PROJESİ', label: 'MALİYET PROJESİ' },
  { value: 'HAK EDİŞ PROJESİ', label: 'HAK EDİŞ PROJESİ' },
  { value: 'PEYZAJ PROJESİ', label: 'PEYZAJ PROJESİ' },
]
