export const UstaSub = [
  { value: 'BOYA BADANA', label: 'BOYA BADANA' },
  { value: 'FAYANS DÖŞEME', label: 'FAYANS DÖŞEME' },
  { value: 'ALÇI SIVA İŞLERİ', label: 'ALÇI SIVA İŞLERİ' },
  { value: 'ALÇIPAN İŞLERİ', label: 'ALÇIPAN İŞLERİ' },
  { value: 'DEKORATİF DUVAR BOYAMA', label: 'DEKORATİF DUVAR BOYAMA' },
  { value: 'DUVAR KAĞIDI', label: 'DUVAR KAĞIDI' },
  { value: 'DUVAR ÇITALAMA', label: 'DUVAR ÇITALAMA' },
  { value: 'DUVAR KAPLAMA ', label: 'DUVAR KAPLAMA ' },
  { value: 'DUVARA RESİM YAPMA', label: 'DUVARA RESİM YAPMA' },
  { value: 'ALÇIPAN DUVAR', label: 'ALÇIPAN DUVAR' },
  { value: 'TAŞ DUVAR YAPIMI', label: 'TAŞ DUVAR YAPIMI' },
  { value: 'PARKE', label: 'PARKE' },
  { value: 'EPOKSİ', label: 'EPOKSİ' },
  { value: 'PVC', label: 'PVC' },
  { value: 'KAUÇUK', label: 'KAUÇUK' },
  { value: 'PARKE TAŞI', label: 'PARKE TAŞI' },
  { value: 'HALI', label: 'HALI' },
  { value: 'MERMER', label: 'MERMER' },
  { value: 'BETON', label: 'BETON' },
  { value: 'AKLİRİK', label: 'AKLİRİK' },
  { value: 'CAM BALKON', label: 'CAM BALKON' },
  { value: 'CAM VİTRİN', label: 'CAM VİTRİN' },
  { value: 'CAM KAPI', label: 'CAM KAPI' },
  { value: 'KAPI', label: 'KAPI' },
  { value: 'ÇELİK KAPI', label: 'ÇELİK KAPI' },
  { value: 'DUŞAKABİN', label: 'DUŞAKABİN' },
  { value: 'AKUSTİK PANEL ', label: 'AKUSTİK PANEL' },
  { value: 'BARESOL TAVAN', label: 'BARESOL TAVAN' },
  { value: 'FERFORJE ', label: 'FERFORJE ' },
  { value: 'ÇELİK PROFİL İŞLERİ', label: 'ÇELİK PROFİL İŞLERİ' },
  { value: 'HALIFLEKS', label: 'HALIFLEKS' },
  { value: 'KARO HALI UYGULAMASI', label: 'KARO HALI UYGULAMASI' },
  { value: 'HAMAM - SAUNA', label: 'HAMAM - SAUNA' },
  { value: 'SU İZOLASYON ', label: 'SU İZOLASYON ' },
  { value: 'ISI İZOLASYON', label: 'ISI İZOLASYON' },
  { value: 'MANTOLAMA', label: 'MANTOLAMA' },
  { value: 'KORKULUK İŞLERİ', label: 'KORKULUK İŞLERİ' },
  { value: 'PEYZAJ İŞLERİ', label: 'PEYZAJ İŞLERİ' },
  { value: 'MERDİVEN İŞLERİ', label: 'MERDİVEN İŞLERİ' },
  { value: 'MERMER İŞLERİ', label: 'MERMER İŞLERİ' },
  { value: 'PERDE İŞLERİ', label: 'PERDE İŞLERİ' },
  { value: 'ŞAP ATIMI', label: 'ŞAP ATIMI' },
  { value: 'TAVAN SİSTEMLERİ', label: 'TAVAN SİSTEMLERİ' },
  { value: 'ELEKTİRİK İŞLERİ', label: 'ELEKTİRİK İŞLERİ' },
  { value: 'SU TESİSAT İŞLERİ', label: 'SU TESİSAT İŞLERİ' },
  { value: 'TOTEM', label: 'TOTEM' },
  { value: 'PİLON', label: 'PİLON' },
  { value: 'TABELA', label: 'TABELA' },
  { value: 'İÇ MEKAN REKLAM', label: 'İÇ MEKAN REKLAM' },
  { value: 'KART VİSİT', label: 'KART VİSİT' },
  { value: 'ZEMİN YÜKSELTME İŞLERİ', label: 'ZEMİN YÜKSELTME İŞLERİ' },
  { value: 'ASMA TAVAN', label: 'ASMA TAVAN' },
  { value: 'BAHÇE ', label: 'BAHÇE ' },
  { value: 'ÇATI İZOLASYON', label: 'ÇATI İZOLASYON' },
  { value: 'İZOLASYON', label: 'İZOLASYON' },
  { value: 'ÇATI İMALATI', label: 'ÇATI İMALATI' },
  { value: 'DEMİR KAYNAK İŞLERİ', label: 'DEMİR KAYNAK İŞLERİ' },
  { value: 'DIŞ CEPHE KAPLAMA', label: 'DIŞ CEPHE KAPLAMA' },
  { value: 'HAVUZ', label: 'HAVUZ' },
  { value: 'KEPENK', label: 'KEPENK' },
  { value: 'PİMAPEN', label: 'PİMAPEN' },
  { value: 'PENCERE', label: 'PENCERE' },
  { value: 'MARANGOZ', label: 'MARANGOZ' },
  { value: 'OTOMATİK KAPI', label: 'OTOMATİK KAPI' },
  { value: 'YÜRÜYEN MERDİVEN', label: 'YÜRÜYEN MERDİVEN' },
  { value: 'ASANSÖR', label: 'ASANSÖR' },
  { value: 'PANJUR', label: 'PANJUR' },
  { value: 'PARKE SİSTRE CİLA', label: 'PARKE SİSTRE CİLA' },
]
