export const YazilimType = [
  { value: 'C', label: 'C' },
  { value: 'JAVA', label: 'JAVA' },
  { value: 'C++', label: 'C++' },
  { value: 'PHP', label: 'PHP' },
  { value: 'PYTHON', label: 'PYTHON' },
  { value: 'C#', label: 'C#' },
  { value: 'JAVASCRIPT', label: 'JAVASCRIPT' },
  { value: 'TYPESCRIPT', label: 'TYPESCRIPT' },
  { value: 'VB.NET', label: 'VB.NET' },
  { value: 'R', label: 'R' },
  { value: 'SQL', label: 'SQL' },
  { value: 'GO', label: 'GO' },
  { value: 'SWIFT', label: 'SWIFT' },
  { value: 'PERL', label: 'PERL' },
  { value: 'RUBY', label: 'RUBY' },
  { value: 'ASSEMBLY LANGUAGE', label: 'ASSEMBLY LANGUAGE' },
  { value: 'MATLAB', label: 'MATLAB' },
  { value: 'CLASSIC VISUAL BASIC', label: 'CLASSIC VISUAL BASIC' },
  { value: 'OBJECTIVE-C', label: 'OBJECTIVE-C' },
  { value: 'RUST', label: 'RUST' },
  { value: 'DART', label: 'DART' },
  { value: 'D', label: 'D' },
  { value: 'KOTLIN', label: 'KOTLIN' },
  { value: 'ELIXIR', label: 'ELIXIR' },
]
